[package]
name = "Rocket-Hello"
version = "0.1.0"
authors = ["felixfaisal <faisalahmedfarooq46@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"